//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomComponents.ConsoleApplication.ORMs.EFGenerated
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public int categoryId { get; set; }
        public string name { get; set; }
        public System.DateTime creationDate { get; set; }
        public System.DateTime lastModifiedDate { get; set; }
        public string extraInfo { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
